# vintrick-backend/app/schemas/blend.py
from pydantic import BaseModel
from typing import Optional

class BlendBase(BaseModel):
    Title: Optional[str] = None
    Brand: Optional[str] = None
    Varietal: Optional[str] = None
    Vintage: Optional[str] = None
    WineType: Optional[str] = None

    # Bulk_x0023_: Optional[str] = None
    # SpecSheet: Optional[str] = None
    # AVA: Optional[str] = None
    # Active: Optional[str] = None
    # ExpectedBottleDate: Optional[str] = None
    # StartingRS: Optional[float] = None
    # TargetRS_x0028_g_x002f_L_x0029_: Optional[float] = None
    # Sweetener: Optional[str] = None
    # CuAddRate: Optional[float] = None
    # FinishingMalic_x0028_ppm_x0029_: Optional[float] = None
    # FinishPVPP_x0028_ppm_x0029_: Optional[float] = None
    # TargetCO2Min_x0028_ppm_x0029_: Optional[float] = None
    # TargetMaxCO2_x0028_ppm_x0029_: Optional[float] = None
    # VelcorinNeeded_x0028_Y_x002f_N_x: Optional[str] = None
    # BottleCO2Min: Optional[float] = None
    # BottleCO2Max: Optional[float] = None
    # DITRate: Optional[float] = None
    # StabivinSP1gal_x002f_1000gal: Optional[str] = None
    # SurliVelvetPlus: Optional[str] = None
    # ML_x003f_: Optional[str] = None
    # Screwcap_x0028_0_x002e_1ppmCu_x0: Optional[str] = None
    # Alc: Optional[float] = None
    # PreFilter: Optional[str] = None
    # FinalFilter: Optional[str] = None
    # Tier: Optional[str] = None
    # LabelAlc: Optional[str] = None
    # Lot_x0023_: Optional[str] = None
    # IsFirstBottling: Optional[str] = None
    # HasAllergens: Optional[str] = None
    # TotalAcidity_x0028_g_x002f_100ml: Optional[float] = None
    # PH: Optional[float] = None
    # SulphurDioxide_x0028_mg_x002f_l_: Optional[float] = None
    # Malate_x0028_mg_x002f_l_x0029_: Optional[str] = None
    # RSInvert_x0028_g_x002f_100ml_x00: Optional[str] = None
    # BottleDORange_x0028_Min_x002f_Ma: Optional[str] = None
    # RS_x0020_Approval_x0020_Min_x002: Optional[str] = None
    # RS_x0020_Approval_x0020_Max_x002: Optional[str] = None
    # RS_x0020_Approval_x0020_Range_x0: Optional[str] = None
    # Bottling_x0020_CO2_x0020_Range_x: Optional[str] = None
    # Bottling_x0020_SO2_x0020_ppm_x00: Optional[str] = None
    # Bottling_x0020_Alc_x0020_Range_x: Optional[str] = None
    # Bottling_x0020_Alc_x0020_Range_x0: Optional[str] = None
    # Bottling_x0020_Alcohol_x0020_Ran: Optional[str] = None
    # Malic_x0028_ppm_x0029_: Optional[float] = None
    # PVPP_x0028_ppm_x0029_: Optional[float] = None
    # Lactic_x0028_ppm_x0029_: Optional[float] = None
    # Arabinol_x0028_gal_x002f_1000gal: Optional[float] = None
    # KWKRate_x0028__x0023__x002f_1000: Optional[float] = None
    # CofTRate_x0028__x0023__x002f_100: Optional[float] = None
    # HeatStable_x0028_Y_x002f_N_x0029: Optional[bool] = None
    # XF_x002f_STARS: Optional[bool] = None
    # Cu_x0028_ppm_x0029_: Optional[float] = None
    # ContentTypeId: Optional[str] = None
    # _ModerationComments: Optional[str] = None
    # File_x0020_Type: Optional[str] = None
    # _ColorHex: Optional[str] = None
    # _ColorTag: Optional[str] = None
    # _Emoji: Optional[str] = None
    # ComplianceAssetId: Optional[str] = None
    # LinkTitleNoMenu: Optional[str] = None
    # LinkTitle: Optional[str] = None
    # LinkTitle2: Optional[str] = None
    # RS_x0020_Approval_x0020_Min_x0020: Optional[str] = None
    # RS_x0020_Approval_x0020_Max_x0020: Optional[str] = None
    # SO2_x0020_Min_x0020__x0028_ppm_x: Optional[str] = None
    # SO2_x0020_Max_x0020__x0028_ppm_x: Optional[str] = None
    # RS_x0020_Approval_x0020_Range_x00: Optional[str] = None
    # Extract_x0028_g_x002f_L_x0029_: Optional[float] = None
    # Extract_x0020_Min_x0020__x0028_g: Optional[str] = None
    # Extract_x0020_Max_x0020__x0028_g: Optional[str] = None
    # Extract_x0020_Range_x0020__x0028: Optional[str] = None
    # Bottling_x0020_SO2_x0020_ppm_x000: Optional[str] = None
    # Extract_x0020_Range_x0020__x00280: Optional[str] = None
    # RS_x0020_Approval_x0020_Range_x01: Optional[str] = None
    # Step1: Optional[str] = None
    # Step2: Optional[str] = None
    # Step3: Optional[str] = None
    # Step4: Optional[str] = None
    # Step5: Optional[str] = None
    # Step6: Optional[str] = None
    # Step1Comments: Optional[str] = None
    # Step2Comments: Optional[str] = None
    # Step3Comments: Optional[str] = None
    # Test_x0020_Label: Optional[str] = None
    # Vintage_x0020_Roll: Optional[str] = None
    # Donotuse: Optional[str] = None
    # Allergens: Optional[str] = None
    # BottlingSO2ppm_x0028_min_x0029_O: Optional[float] = None
    # BottlingSO2ppm_x0028_max_x0029_O: Optional[float] = None
    # RSApprovalRangerg_x002f_L_x0028_: Optional[float] = None
    # RSApprovalRangerg_x002f_L_x0028_0: Optional[float] = None
    # Extractg_x002f_L_x0028_Min_x0029: Optional[float] = None
    # Extractg_x002f_L_x0028_Max_x0029: Optional[float] = None
    # Label_x0020_1: Optional[str] = None
    # CO2_x0020_Override: Optional[str] = None
    # Vegan_x003f_: Optional[str] = None
    # CO2_x0020_Tanker_x0020_Min_x0020: Optional[float] = None
    # CO2_x0020_Tanker_x0020_Max_x0020: Optional[float] = None
    # Malate_x0020__x0028_g_x002f_L_x0: Optional[str] = None
    # Tech_x0020_Sheet_x0020_Needed: Optional[str] = None
    # Wine_x0020_Library_x0020_Order_x: Optional[str] = None
    # Label_x0020_Verification_x0020_N: Optional[str] = None
    # FinishingCu: Optional[str] = None
    # FirstBottlingRun: Optional[str] = None
    # FG_x0020_sub_x0020_1: Optional[str] = None
    # FG_x0020_sub_x0020_2: Optional[str] = None
    # Date_x0020_Notified: Optional[str] = None
    # Notified_x0020_By: Optional[str] = None
    # ID: Optional[int] = None
    # ContentType: Optional[str] = None
    # Modified: Optional[str] = None
    # Created: Optional[str] = None
    # Author: Optional[str] = None
    # Editor: Optional[str] = None
    # _HasCopyDestinations: Optional[bool] = None
    # _CopySource: Optional[str] = None
    # owshiddenversion: Optional[int] = None
    # WorkflowVersion: Optional[int] = None
    # _UIVersion: Optional[int] = None
    # _UIVersionString: Optional[str] = None
    # Attachments: Optional[bool] = None
    # _ModerationStatus: Optional[str] = None
    # Edit: Optional[str] = None
    # SelectTitle: Optional[str] = None
    # InstanceID: Optional[int] = None
    # Order: Optional[float] = None
    # GUID: Optional[str] = None
    # WorkflowInstanceID: Optional[str] = None
    # FileRef: Optional[str] = None
    # FileDirRef: Optional[str] = None
    # Last_x0020_Modified: Optional[str] = None
    # Created_x0020_Date: Optional[str] = None
    # FSObjType: Optional[str] = None
    # SortBehavior: Optional[str] = None
    # PermMask: Optional[str] = None
    # PrincipalCount: Optional[str] = None
    # FileLeafRef: Optional[str] = None
    # UniqueId: Optional[str] = None
    # ParentUniqueId: Optional[str] = None
    # SyncClientId: Optional[str] = None
    # ProgId: Optional[str] = None
    # ScopeId: Optional[str] = None
    # HTML_x0020_File_x0020_Type: Optional[str] = None
    # _EditMenuTableStart: Optional[str] = None
    # _EditMenuTableStart2: Optional[str] = None
    # _EditMenuTableEnd: Optional[str] = None
    # LinkFilenameNoMenu: Optional[str] = None
    # LinkFilename: Optional[str] = None
    # LinkFilename2: Optional[str] = None
    # DocIcon: Optional[str] = None
    # ServerUrl: Optional[str] = None
    # EncodedAbsUrl: Optional[str] = None
    # BaseName: Optional[str] = None
    # MetaInfo: Optional[str] = None
    # _Level: Optional[int] = None
    # _IsCurrentVersion: Optional[bool] = None
    # ItemChildCount: Optional[str] = None
    # FolderChildCount: Optional[str] = None
    # Restricted: Optional[str] = None
    # OriginatorId: Optional[str] = None
    # NoExecute: Optional[str] = None
    # ContentVersion: Optional[str] = None
    # _ComplianceFlags: Optional[str] = None
    # _ComplianceTag: Optional[str] = None
    # _ComplianceTagWrittenTime: Optional[str] = None
    # _ComplianceTagUserId: Optional[str] = None
    # _IsRecord: Optional[str] = None
    # AccessPolicy: Optional[str] = None
    # _VirusStatus: Optional[str] = None
    # _VirusVendorID: Optional[str] = None
    # _VirusInfo: Optional[str] = None
    # _RansomwareAnomalyMetaInfo: Optional[str] = None
    # _DraftOwnerId: Optional[str] = None
    # MainLinkSettings: Optional[str] = None
    # AppAuthor: Optional[str] = None
    # AppEditor: Optional[str] = None
    # SMTotalSize: Optional[str] = None
    # SMLastModifiedDate: Optional[str] = None
    # SMTotalFileStreamSize: Optional[str] = None
    # SMTotalFileCount: Optional[str] = None
    # _CommentFlags: Optional[str] = None
    # _CommentCount: Optional[str] = None

class BlendCreate(BlendBase):
    pass

class BlendUpdate(BlendBase):
    pass

class BlendOut(BlendBase):
    ID: int

    class Config:
        from_attributes = True
        populate_by_name = True